FROM nginx:alpine

# Copy built app from the previous stage
COPY --from=build /usr/src/app /usr/src/app

# Copy custom Nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Expose the HTTPS port
EXPOSE 443

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]
