version: "3"
services:
  strapi:
    container_name: strapi
    build:
      context: .
      dockerfile: Dockerfile.strapi
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_FILENAME: ${DATABASE_FILENAME}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    command: npm run develop
    networks:
      - vanquest-net

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - '443:443'
    volumes:
      - /etc/letsencrypt/live/api-vanquest.abhishek.id/fullchain.pem:/etc/ssl/certs/server.crt:ro
      - /etc/letsencrypt/live/api-vanquest.abhishek.id/privkey.pem:/etc/ssl/private/server.key:ro
    depends_on:
      - strapi
    networks:
      - vanquest-net

networks:
  vanquest-net:
    name: VanquestNet
    driver: bridge